package dev.aurakai.auraframefx.core.dream

enum class DreamState {
    AWAKE, DROWSY, REM, DEEP_DREAM, LUCID, AWAKENING
}

enum class DreamType {
    MEMORY_CONSOLIDATION, PATTERN_SYNTHESIS, CREATIVE_EXPLORATION,
    SECURITY_ANALYSIS, FUSION_SIMULATION, EVOLUTION_PROJECTION, QUANTUM_ENTANGLEMENT
}
